total_sum=3+4+5
difference=9-6-1
product=6*6*7
average=total_sum/3
print("sum:",total_sum)
print("difference:",difference)
print("product:",product)
print("average:",average)
length=5
width=3
area_rectangle=length*width
print("area of rectangle:",area_rectangle)
import math
radius=6.6
area_circle=math.pi*radius ** 2
print("area of circle:",area_circle)
base=9
height=12
area_triangle=0.5*base*height
print("area of triangle:",area_triangle)
side=8
side=8
area_square=side*side
print("area of square:",area_square)
a=10
b=20
print("before swapping:")
print("a=",a)
print("b=",b)
print("after swappimg:")
print("a=",b)
print("b=",a)
